/* Project Euler - 012 - Highly divisible triangular number
 * Copyright (c) 2019 Tamara Roberson
 *
 * The sequence of triangle numbers is generated by adding the natural numbers.
 * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The
 * first ten terms would be:
 *
 *      1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 *
 * Let us list the factors of the first seven triangle numbers:
 *
 *       1: 1
 *       3: 1,3
 *       6: 1,2,3,6
 *      10: 1,2,5,10
 *      15: 1,3,5,15
 *      21: 1,3,7,21
 *      28: 1,2,4,7,14,28
 *
 *  We can see that 28 is the first triangle number to have over five divisors.
 *
 *  What is the value of the first triangle number to have over five hundred
 *  divisors?
 */

namespace euler
{

/**
 * Solves the example problem.
 *
 * 28 is the first triangle number to have over five divisors.
 *
 * @returns the solution to the problem.
 */
int euler012_example();


/**
 * Solves the problem.
 *
 * What is the value of the first triangle number to have over five hundred
 * divisors?
 *
 * @returns the solution to the problem.
 */
int euler012();



} // end namespace euler
